Fuzz with latest MSRV
The daily fuzzing job is borked

error: package `syn v2.0.108` cannot be built because it requires rustc 1.68 or newer, while the currently active rustc version is 1.65.0
Either upgrade to rustc 1.68 or newer, or use
cargo update -p syn@2.0.108 --precise ver
where `ver` is the latest version of `syn` supporting rustc 1.65.0

Use the latest MSRV when fuzzing.