Explicitly depend on newly released bech32 version
I woke up this morning to the compiler emitting:

    error[E0308]: mismatched types

At first I thought it was another nightly thing like yesterday but it
turns out its because of the latest `bech32` release.

Because we use `0.10.0-beta` the new release gets pulled down
automatically (well at least I think it does), but I'm getting strange
errors in CI so lets just explicitly depend on the new release.